# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'avalon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # add pods for desired Firebase products
  # Pods for avalon
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'avalonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'avalonUITests' do
    # Pods for testing
  end

end
